### ISSUE TITLE
Oasis CLI 1.0  (Release 3)

### ISSUE THREAD

**Issue by eauge** [oasislabs/oasis-cli#25]
- [x] mantle build check `rustc --version` (https://github.com/oasislabs/oasis-cli/issues/28)
 - [x] oasis deploy --dashboard (https://github.com/oasislabs/oasis-cli/issues/22)
 - [x] logging generation (https://github.com/oasislabs/oasis-cli/issues/23)
 - [x] telemetry (https://github.com/oasislabs/oasis-cli/issues/24, https://github.com/oasislabs/oasis-cli/issues/40)
 - [x] oasis configuration (https://github.com/oasislabs/oasis-cli/issues/26)
 - [x] user identity (https://github.com/oasislabs/oasis-cli/issues/29)
